### ISSUE TITLE
Oscillating VESC

### ISSUE THREAD

**Issue by Galto2000** [mit-racecar/vesc#4]
Howdy,

I am using the joy_teleop node, the ackermann_mux node, the ackermann_to_vesc node and a vesc node to drive a Traxxas EMAXX with brushless motor. Since the EMAXX has dual steering servo, I am not controlling this via the VESC but via other dedicated hardware.

The issue I have is that when I operate in teleop mode (I am using the same Logitech game-pad), and I apply speed command, then very often the motor RPM oscillates rather violently (making a rattling noise as the whole drive-chain vibrates). 

When I monitor /sensor/core, then during the oscillations I can see the speed is all over the place, and the motor current oscillates between 0 and 40 A.

Sometimes this oscillation is followed by a sudden high RPM burst (almost like a "runway") that exceeds the imposed erpm limit values in vesc.yaml. 

I can almost always prevent this from happening if I apply speed very slowly. I experimented with placing a low-pass filter on the erpm command to the vesc: this seems to help somewhat, but I can't set the time constant too high, or it becomes noticeably sluggish. 

In my experience this issue doesn't care whether there is a lot of load on the wheels (e.g. when I place the EMAXX on the ground), or little load (when I lift the EMAXX off the ground, so the wheels are free spinning).

I was wondering if perhaps anyone else has seen this issue, or perhaps has some ideas.

Thanks

Galto

**Comment by mboulet** [comment]
Hi,

The VESC requires that you tune parameters for each motor. See the "Motor Configuration" section on VESC website http://vedder.se/2015/01/vesc-open-source-esc/. He also has a video. Tuning motors for small vehicles tends to be tricky due to the low inductance.

Vedder's VESC GUI sends commands to the VESC the same way that the ROS node does. If you can get the motor to run smoothly with the GUI, you should see similar performance with the ROS node.

Mike

**Comment by Galto2000** [comment]
Thanks for the information Mike

Galto
